### PR TITLE
Basic files to add SBC gamepad support

### PR DESCRIPTION
**Pull request by RadWolfie**
@ergo720, is there any other new files need to be add?

### CODE REVIEW

**Comment by ergo720** [comment]
@LanHikariDS Please wait before merging this PR, I'll submit a new one.

**Comment by LanHikariDS** [comment]
I should probably push my current changes as well

**Comment by RadWolfie** [comment]
Okay, this should be all the new files needed to work on. Plus they are only clone with renamed functions/variables.

**EDIT:**
Also, will need pull request https://github.com/LanHikariDS/Cxbx-Reloaded/pull/2 merge before start using new files to work on.

**Comment by ergo720** [comment]
To avoid confusing @LanHikariDS, I think it's better not to add the XidSBCGamepad files entirely. This, because the USB requests that it uses have not been reversed yet, and thus just copying them from the xbox controller might be incorrect. Especially with the function UpdateForceFeedback(), which is used by the rumble functionality and we know that the SBC doesn't rumble so that's definitely wrong.

**Comment by RadWolfie** [comment]
Done, also removed unnecessary functions from new file.

**Comment by LanHikariDS** [comment]
For some odd reason, Github isn't letting me sort through conflicts through browser on this PR, but *did* let me do so with PR #2, so I'm going to have to manually add in the changes from this PR

**Comment by RadWolfie** [comment]
Resolved merge conflict.

**Pull request merged**
